/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List File Rows */
        get: operations["list_file_rows_files_get"];
        put?: never;
        /** Upload File */
        post: operations["upload_file_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File */
        get: operations["get_file_files__file_id__get"];
        put?: never;
        post?: never;
        /** Delete File */
        delete: operations["delete_file_files__file_id__delete"];
        options?: never;
        head?: never;
        /** Patch File */
        patch: operations["patch_file_files__file_id__patch"];
        trace?: never;
    };
    "/files/{file_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File Content */
        get: operations["get_file_content_files__file_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}/bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Binding */
        post: operations["create_binding_files__file_id__bindings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}/bindings/{binding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Binding */
        delete: operations["delete_binding_files__file_id__bindings__binding_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views/file-browser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** File Browser */
        get: operations["file_browser_views_file_browser_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_file_files_post */
        Body_upload_file_files_post: {
            /** File */
            file: string;
            /** Kind */
            kind: string;
            /** Workspace Id */
            workspace_id: string;
            /** Project Id */
            project_id?: string | null;
            /** Binding Type */
            binding_type?: string | null;
            /** Binding Id */
            binding_id?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /** FileBindingCreate */
        FileBindingCreate: {
            /** Binding Type */
            binding_type: string;
            /** Binding Id */
            binding_id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Project Id */
            project_id?: string | null;
        };
        /** FileBindingOut */
        FileBindingOut: {
            /** Id */
            id: string;
            /** Binding Type */
            binding_type: string;
            /** Binding Id */
            binding_id: string;
        };
        /** FileBrowserCrumbOut */
        FileBrowserCrumbOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** FileBrowserItemOut */
        FileBrowserItemOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Mime Type */
            mime_type: string;
            /** Byte Size */
            byte_size: number;
            /** Original Filename */
            original_filename: string;
            /** Width Px */
            width_px?: number | null;
            /** Height Px */
            height_px?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Workspace Id */
            workspace_id: string;
            /** Project Id */
            project_id?: string | null;
            /** Folder Id */
            folder_id?: string | null;
            created_by?: components["schemas"]["UserBrief"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Bindings */
            bindings?: components["schemas"]["FileBindingOut"][];
            /** Content Path */
            content_path: string;
            /** Thumb Path */
            thumb_path?: string | null;
            /** Poster Path */
            poster_path?: string | null;
            /** Size Label */
            size_label: string;
        };
        /** FileBrowserTotalsOut */
        FileBrowserTotalsOut: {
            /** File Count */
            file_count: number;
            /** Byte Size */
            byte_size: number;
        };
        /** FileBrowserViewOut */
        FileBrowserViewOut: {
            /** Workspace Id */
            workspace_id: string;
            /** Workspace Name */
            workspace_name: string;
            /** Project Id */
            project_id?: string | null;
            /** Project Name */
            project_name?: string | null;
            /** Folder Id */
            folder_id?: string | null;
            /** Folder Name */
            folder_name?: string | null;
            /** Crumbs */
            crumbs?: components["schemas"]["FileBrowserCrumbOut"][];
            /** Folders */
            folders?: {
                [key: string]: unknown;
            }[];
            /** Files */
            files?: components["schemas"]["FileBrowserItemOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            totals: components["schemas"]["FileBrowserTotalsOut"];
        };
        /** FileListOut */
        FileListOut: {
            /** Items */
            items?: components["schemas"]["FileOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** FileOut */
        FileOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Mime Type */
            mime_type: string;
            /** Byte Size */
            byte_size: number;
            /** Original Filename */
            original_filename: string;
            /** Width Px */
            width_px?: number | null;
            /** Height Px */
            height_px?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Workspace Id */
            workspace_id: string;
            /** Project Id */
            project_id?: string | null;
            /** Folder Id */
            folder_id?: string | null;
            created_by?: components["schemas"]["UserBrief"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Bindings */
            bindings?: components["schemas"]["FileBindingOut"][];
            /** Content Path */
            content_path: string;
            /** Thumb Path */
            thumb_path?: string | null;
            /** Poster Path */
            poster_path?: string | null;
        };
        /** FileUpdate */
        FileUpdate: {
            /** Original Filename */
            original_filename?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** UserBrief */
        UserBrief: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_file_rows_files_get: {
        parameters: {
            query: {
                workspace_id: string;
                project_id?: string | null;
                kind?: string | null;
                binding_type?: string | null;
                binding_id?: string | null;
                q?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_files_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_files__file_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_file_files__file_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_file_files__file_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_content_files__file_id__content_get: {
        parameters: {
            query?: {
                variant?: string;
            };
            header?: {
                range?: string | null;
                authorization?: string | null;
            };
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_binding_files__file_id__bindings_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileBindingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_binding_files__file_id__bindings__binding_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                file_id: string;
                binding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    file_browser_views_file_browser_get: {
        parameters: {
            query: {
                workspace_id: string;
                project_id?: string | null;
                folder_id?: string | null;
                kind?: string | null;
                q?: string | null;
                sort?: string;
                order?: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileBrowserViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
