/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#fffbff",
        "inverse-on-surface": "#f2effb",
        "on-secondary-fixed-variant": "#085300",
        "primary-container": "#6063ee",
        "inverse-surface": "#303038",
        "on-error": "#ffffff",
        "on-tertiary-container": "#fffbff",
        outline: "#767586",
        "surface-container-low": "#f5f2fe",
        tertiary: "#904900",
        "primary-hover": "#4F46E5",
        "surface-container-high": "#e9e6f3",
        "on-tertiary-fixed-variant": "#703700",
        "secondary-container": "#86f96a",
        "secondary-fixed-dim": "#6ddf54",
        primary: "#4648d4",
        "outline-variant": "#c7c4d7",
        "on-surface": "#1b1b23",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#c0c1ff",
        success: "#10B981",
        "surface-container-highest": "#e4e1ed",
        "primary-fixed": "#e1e0ff",
        background: "#FAFAFA",
        "surface-tint": "#494bd6",
        "on-secondary": "#ffffff",
        "surface-container": "#efecf8",
        surface: "#FFFFFF",
        "on-tertiary-fixed": "#301400",
        "neutral-muted": "#9C9C9C",
        "secondary-fixed": "#89fc6d",
        "on-surface-variant": "#464554",
        "text-primary": "#0A0A0A",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#07006c",
        secondary: "#0e6e00",
        "tertiary-fixed-dim": "#ffb783",
        "surface-variant": "#e4e1ed",
        "text-secondary": "#6B6B6B",
        "surface-bright": "#fcf8ff",
        "inverse-primary": "#c0c1ff",
        "on-tertiary": "#ffffff",
        warning: "#F59E0B",
        "on-primary-fixed-variant": "#2f2ebe",
        "tertiary-container": "#b55d00",
        "tertiary-fixed": "#ffdcc5",
        "on-secondary-fixed": "#022200",
        "on-background": "#1b1b23",
        "on-secondary-container": "#0f7300",
        "surface-dim": "#dbd8e4",
        "border-subtle": "#E8E8EC",
        error: "#EF4444",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "8xl": "96px",
        "2xl": "24px",
        "container-max": "1280px",
        base: "4px",
        "3xl": "32px",
        "5xl": "48px",
        xs: "4px",
        lg: "16px",
        "6xl": "64px",
        sm: "8px",
        xl: "20px",
        "7xl": "80px",
        "4xl": "40px",
        "container-padding": "24px",
        gutter: "24px",
        md: "12px",
      },
      fontFamily: {
        "section-heading": ["var(--font-epilogue)"],
        body: ["var(--font-be-vietnam)", "ui-sans-serif", "system-ui"],
        display: ["var(--font-epilogue)"],
        headline: ["var(--font-epilogue)"],
        caption: ["var(--font-be-vietnam)"],
        small: ["var(--font-be-vietnam)"],
        code: ["var(--font-jetbrains-mono)", "ui-monospace", "SFMono-Regular"],
        overline: ["var(--font-be-vietnam)"],
        subhead: ["var(--font-epilogue)"],
      },
      fontSize: {
        "section-heading": ["32px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "700" }],
        body: ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        display: ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        headline: ["60px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        small: ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        code: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        overline: ["11px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        subhead: ["24px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

